name: தொடர்ச்சியான ஒருங்கிணைப்பு

on:
  push:
    branches:
      - முதன்மை

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  nool-kattu:
    runs-on: ubuntu-latest

    steps:

      - name: கோப்புகளைப் பெறுதல்
        uses: actions/checkout@v6

      - name: சார்புகளை நிறுவவும்
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonttools \
            wget \
            xz-utils \
            libegl1 \
            libopengl0 \
            libgl1 \
            libxkbcommon0 \
            libxkbcommon-x11-0 \
            libxcb-cursor0

      - name: புதிய கலிப்ரேவை நிறுவுதல்
        run: |
          wget -nv https://download.calibre-ebook.com/linux-installer.sh
          sudo sh linux-installer.sh

      - name: தமிழ் எழுத்துருக்களை தீநரிக்கு ஏற்றவாறு சரிசெய்தல்
        run: |
          python3 /.py

      - name: தமிழ் எழுத்துருக்களை நிறுவுதல்
        run: |
          sudo mkdir -p /usr/local/share/fonts/tac

          find . -type f -name "TAC-*.ttf" \
            -exec sudo cp {} /usr/local/share/fonts/tac/ \;

          sudo fc-cache -f -v

      - name: முனை.js-ஐ நிறுவுதல்
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: ஆன்கிட்டை நிறுவுதல்
        run: |
          make setup

      - name: ஆன்கிட்டை உருவாக்குதல்
        run: |
          make build
          make pdf
          make epub

      - name: அறிவிலிகுழு பக்கங்கள் அமைத்தல்
        uses: actions/configure-pages@v5

      - name: இணையதளத்தைப் பதிவேற்றுதல்
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./"

      - name: வெளியீட்டு பதிப்பு எண்ணை உருவாக்குதல்
        id: version
        run: |
          MAJOR=$(date -u +"%Y")
          MINOR=$(date -u +"%m%d")
          BUILD=$(date -u +"%H%M")
          VERSION="3.14-${MAJOR}.${MINOR}.${BUILD}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "உருவாக்கிய பதிப்பு: $VERSION"

      - name: வெளியீட்டை உருவாக்குதல்
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${{ steps.version.outputs.version }}"

          cp "./.pdf" "./$TAG.pdf"
          cp "./.epub" "./$TAG.epub"

          gh release create "$TAG" \
            --title "மலைப்பாம்புக்கடி $TAG" \
            --generate-notes

          gh release upload "$TAG" \
            "./$TAG.pdf#மலைப்பாம்புக்கடி.pdf" \
            "./$TAG.epub#மலைப்பாம்புக்கடி.epub" \
            --clobber

  inaiya-nool:
    runs-on: ubuntu-latest

    needs: nool-kattu

    environment:
      name: நூல்
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:

      - name: அறிவிலிகுழு பக்கங்களுக்கு வெளியிடுதல்
        id: deployment
        uses: actions/deploy-pages@v4